### ISSUE TITLE
[Kaggle_Competition] Julia Sabatel (el bueno)

### ISSUE THREAD

**Issue by juliasabatel** [OrianAmpuero/Kaggle_Competition#11]
https://github.com/juliasabatel/Kaggel_Project

**Comment by OrianAmpuero** [comment]
Muy bien Juls! :) Felicidades por tu evolución en el bootcamp, se ha notado tu progreso y el esfuerzo que has hecho día a día, te animo a seguir así. Confía más en tí porque tienes mucho para dar y ha sido un placer tenerte en el #TeamDATA. Te deseo lo mejor para el proyecto y tu futuro en este nuevo camino
