### ISSUE TITLE
[Kaggle Proyecto] Victor

### ISSUE THREAD

**Issue by victorrmtz** [OrianAmpuero/Kaggle_Competition#16]
https://github.com/victorrmtz/Proyecto-Kaggle-Competicion.git

**Comment by OrianAmpuero** [comment]
Muy bien Víctor! Felicidades por tu segundo puesto en la compe. Aprovecho para decirte que has tenido una gran evolución en el bootcamp y sé ha notado el esfuerzo, gracias por tu actitud y por disfrutar de la experiencia. Te deseo lo mejor en el proyecto y en tu nuevo comienzo en DATA :)
