### ISSUE TITLE
[Kaggle_Competition] Javier Garcia

### ISSUE THREAD

**Issue by fjgarciaes** [OrianAmpuero/Kaggle_Competition#18]
https://github.com/fjgarciaes/Competicion-Kaggle

**Comment by AdrianCiges** [comment]
Buen trabajo, el readme lo puedes mejorar, y la presentación muy elegante. Buen curro Javi.
Aprovecho este último feedback de github para felicitarte por tu trabajo durante el bootcamp. Has currado muchísimo y siempre has sacado el trabajo de forma muy solvente. Ha sido un gustazo corregir tus entregas y mención de honor a tu actitud en todo momento y en todos los aspectos. Enhorabuena Javier 👏🏻
A tope con la música y tu proyecto final!
