### ISSUE TITLE
kaggle_competition_Arianne_Murillo

### ISSUE THREAD

**Issue by Arimugon** [OrianAmpuero/Kaggle_Competition#21]
https://github.com/Arimugon/Proyect5_kaggle_Ari.git

**Comment by AdrianCiges** [comment]
Bien organizado el repo, buen readme (quizá pondría más color, tipo emojis y tal). La presentación guay, algo oscura tal vez, pero bastante clara. Buen curro.
Aprovecho este último feedback para felicitarte por todo tu trabajo durante el bootcamp. Has sido una currante y siempre has sacado el trabajo con mucha solvencia. Enhorabuena!
A tope con el proyecto final ;)
