### ISSUE TITLE
[Kaggle_Competition] Arturo

### ISSUE THREAD

**Issue by Artturoo** [OrianAmpuero/Kaggle_Competition#24]
https://github.com/Artturoo/Proyecto-Machine-Learning.git

**Comment by AdrianCiges** [comment]
Arturito! Buen curro, enhorabuena por la competición. Muy buen repo, bien organizado, buen readme y muy explicativo. La presentación muy bien, aunque intentaría quitar texto y poner más imágenes, iconos y similares para reducir la carga de letras, que al oyente siempre lo pueden desconectar.
Aprovecho este último feedback para darte la enhorabuena por tu bootcamp. Has currado un montón y eso se ha notado. Siempre has sacado un buen curro, con muy buena actitud en todos los sentidos. En lo personal, un gustazo haber corregido tus trabajos y tenerte de alumno. Felicidades Arturo!
A tope con el trabajo final ;)
