### ISSUE TITLE
[kaggle_competition] David Cuenca

### ISSUE THREAD

**Issue by kuenk** [OrianAmpuero/Kaggle_Competition#27]
https://github.com/kuenk/kaggle-competition-me-

**Comment by AdrianCiges** [comment]
Buen trabajo, pero el repo debe tener un readme tuyo, no ser un fork del nuestro, pillín. Intenta organizar mejor el repo. La presentación muy guay.
Aprovecho este último feedback para felicitarte por todo tu trabajo durante el bootcamp. Has sacado siempre el trabajo con solvencia y eres un trabajador incansable. Muy buena actitud siempre. Enhorabuena!
