### ISSUE TITLE
Silvia Barge

### ISSUE THREAD

**Issue by Barge7** [OrianAmpuero/Kaggle_Competition#32]
https://github.com/Barge7/Kaggle_Competition

**Comment by OrianAmpuero** [comment]
Bien Silvia!! Te animo a mejorar el repo para tenerlo también como portfolio. Por otra parte, aprovecho de felicitarte por tu progreso en el bootcamp, gracias por tu actitud, por hacernos reír y por disfrutar de la experiencia. Te deseo lo mejor en el proyecto final y en tu nuevo camino en DATA :)
