### ISSUE TITLE
[Kaggle_Competition] María Miño

### ISSUE THREAD

**Issue by mariamino** [OrianAmpuero/Kaggle_Competition#41]
https://github.com/mariamino/Salary_Prediction.git

**Comment by OrianAmpuero** [comment]
María! Te animo a mejorar este repo porque esta bien que practiques los modelos predictivos y los tengas como portfolio. A parte de eso, quería aprovechar de felicitarte por tu evolución, se ha notado el crecimiento que has logrado en el bootcamp y las ganas de aprender. Te deseo lo mejor para el proyecto y en tu futuro como Data Analyst :)
