### ISSUE TITLE
[Kaggle_Competition] Nony

### ISSUE THREAD

**Issue by jquintanac** [OrianAmpuero/Kaggle_Competition#7]
https://github.com/jquintanac/ML-Kaggle

**Comment by OrianAmpuero** [comment]
Nony! Excelente trabajo, felicidades por tu 3er puesto en la compe y ya te digo que merecido porque has tenido una evolución muy buena, has ido creciendo y sé que seguirá siendo así; nos has sorprendido a bien, tienes una personalidad muy especial, dejas huella donde pasas y te animo a confiar en tí y en tus habilidades! Te deseo lo mejor para el proyecto :)
