### ISSUE TITLE
[Kaggle_Competition] David Tejedor

### ISSUE THREAD

**Issue by Davidteje** [OrianAmpuero/Kaggle_Competition#8]
https://github.com/Davidteje/Kaggle_Competition_Salary_Prediction

**Comment by AdrianCiges** [comment]
Buen trabajo, muy bien organizado el repo y buen readme. Quizá le pondría emojis o imágenes para darle más color y enganchar más al lector. La presentación guay pero de cara a tu trabajo final, te aconsejo reducir la carga de texto lo más posible e incluir elementos visuales como imágenes, iconos y similares que representen lo que quieres explicar y seas tu quien lleve la carga explicativa durante la exposición oral, así enganchas más a la audiencia. 
Aprovecho este último feedback para darte la enhorabuena por el bootcamp que has hecho, David (y ya tenía pensado este texto antes de tus últimos comentarios jajaja). Has sido un auténtico currante, siempre has sacado el trabajo con mucha solvencia y además muy muy muy buen actitud. De verdad, ha sido todo un gustazo corregir tu trabajo y orientarte durante el curso. De 10, David! 
A tope con el trabajo final ⚽
